# Generated by Django 5.1.6 on 2025-02-21 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('hire_date', models.DateField()),
                ('employee_role', models.CharField(choices=[('manager', 'manager'), ('sales_associate', 'sales_associate'), ('inventory_clerk', 'inventory_clerk')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'in_stock'), ('out_of_stock', 'out_of_stock'), ('discontinued', 'discontinued')], default='in_stock'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'card'), ('digital wallet', 'digital wallet'), ('cash', 'cash')])),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid'), ('pending', 'pending')], default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customers', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='bookstore.customers')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bookstore.orders')),
            ],
        ),
    ]
