# Generated by Django 5.1.6 on 2025-02-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_employees_books_stock_status_orders_order_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customers',
        ),
    ]
