# Generated by Django 5.1.6 on 2025-02-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_rename_orders_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='Categories',
        ),
    ]
