# Generated by Django 5.1.6 on 2025-03-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_category_user_order_user_book_authors_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
