# Generated by Django 5.1.6 on 2025-03-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
